export const FORMULARIO_RENTAS = "OBTENER_PUBLICACIONES";

export const OBTENER_RENTAS = "OBTENER_RENTAS";
export const AGREGAR_RENTA = "AGREGAR_RENTA";
export const VALIDAR_RENTA = "VALIDAR_RENTA";
export const ELIMINAR_RENTA = "ELIMINAR_RENTA";
export const RENTA_ACTUAL = "RENTA_ACTUAL";
export const ACTUALIZAR_RENTA = "ACTUALIZAR_RENTA";
export const LIMPIAR_RENTA = "LIMPIAR_RENTA";
export const OBTENER_RENTAS_TIPO = "OBTENER_RENTAS_TIPO";

//TYPES PARA RENTAS

export const REGISTRO_EXITOSO = "REGISTRO_EXITOSO";
export const REGISTRO_ERROR = "REGISTRO_ERROR";
export const OBTENER_USUARIO = "OBTENER_USUARIO";
export const LOGIN_EXITOSO = "LOGIN_EXITOSO";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const CERRAR_SESION = "CERRAR_SESION";
